[project]
authors = ["Brymer Meneses <68867487+brymer-meneses@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community"]
description = "Add a short description here"
name = "damath-zero"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
server = "mojo src/server.mojo"

[dependencies]
max = ">=25, <26"
small_time = "0.0.2.*"
requests = ">=2.32.3,<3"
fastapi = ">=0.115.8,<0.116"